from typing import Any, Protocol


class StateRepository(Protocol):
    def get(self, camera_id: str) -> dict[str, Any]: ...

    def set_bowl_position(self, camera_id: str, bowl: dict[str, int]) -> None: ...


class FrameRepository(Protocol):
    def init_schema(self) -> None: ...

    def save_upload(self, camera_id: str, index: int, filename: str, image_bytes: bytes) -> str: ...

    def read_file_bytes(self, file_path: str) -> bytes: ...

    def insert_frame(
        self,
        camera_id: str,
        request_id: str,
        original_filename: str,
        file_path: str,
        file_size: int,
        image_timestamp: float,
        source: str = "upload",
    ) -> int: ...

    def get_frame_by_id(self, frame_id: int) -> dict[str, Any] | None: ...

    def get_frames_in_window(self, camera_id: str, latest_ts: float, window_seconds: int) -> list[dict[str, Any]]: ...

    def touch_frames(self, frame_ids: list[int]) -> None: ...

    def mark_frames_status(self, frame_ids: list[int], status: str) -> None: ...

    def evict_lru_frames(self, camera_id: str) -> None: ...

    def update_frame_detection(self, frame_id: int, analysis: dict[str, Any]) -> None: ...

    def get_latest_detected_frame(self, camera_id: str, before_ts: float) -> dict[str, Any] | None: ...

    def insert_analysis_record(self, camera_id: str, timestamp_value: float, analysis: dict[str, Any]) -> None: ...

    def get_all_history(self, camera_id: str) -> list[dict[str, Any]]: ...
