server:
  port: 8081

spring:
  application:
    name: yingshi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yingshi_database?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 23050929
  
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hamster.yingshi.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: HamsterAIoT2026SecretKeyForJWTTokenGeneration
  expiration: 86400000

ezviz:
  app-key: ef6f78de7878472d924ed3e2347c66ec
  app-secret: 13e02bd12ac38cd466e2b51556700356

ai:
  model: glm-4-flash
  api-url: https://open.bigmodel.cn/api/paas/v4/chat/completions
  api-key: d175f7c031b34c869c2e2d454fcf7b90.uELNrBuyS0jiy3ys
  timeout: 30000
  service-url: http://127.0.0.1:8000

recording:
  enabled: true
  duration-seconds: 300
  space-id: 441218
  template-id: 3624
  space-name: "hamster_default"
  expire-days: 7

alert:
  triggers:
    high: true
    low: false
  dedup-windows:
    high: 30m
    low: 60m
  default-threshold: 30
